apiVersion: plugin.halo.run/v1alpha1
kind: ReverseProxy
metadata:
  name: reverse-proxy-meilisearch
  labels:
    plugin.halo.run/plugin-name: PluginMeilisearch
rules:
  - path: /static/**
    file:
      directory: static
