apiVersion: v1alpha1
kind: Setting
metadata:
  name: meilisearch-engine-setting
spec:
  forms:
    - group: basic
      label: Basic
      formSchema:
        - $formkit: text
          name: host
          required: true
          label: "Meilisearch 服务地址"
          placeholder: "http://localhost:7700"
          help: "需要确保 Halo 服务或者 Halo 所在的容器可以访问到此地址"
        - $formkit: password
          name: masterKey
          required: true
          label: "Meilisearch 主密钥"
          help: "Meilisearch 的 Master Key"
        - $formkit: text
          name: indexName
          label: "索引名称"
          value: "halo"