# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: meilisearch
spec:
  enabled: true
  requires: ">=2.21.0"
  author:
    name: Halo
    website: https://github.com/Halo
  logo: logo.png
  homepage: https://github.com/Halo/meilisearch#readme
  repo: https://github.com/Halo/meilisearch
  issues: https://github.com/Halo/meilisearch/issues
  displayName: "meilisearch"
  description: "meilisearch - Halo 插件"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Halo/meilisearch/blob/main/LICENSE"
