name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    permissions:
      contents: write
    with:
      ui-path: "ui"
      pnpm-version: 10
      node-version: 22
      java-version: 21
      app-id: app-7mb5szjt
